version: '3.3'
services:
  web:
    container_name: waiterapp_backend
    build: ../.
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      POSTGRES_PASSWORD: fred
      POSTGRES_USERNAME: postgres
      POSTGRES_HOST: postgres
      APP_PORT: 8080

  postgres:
    container_name: postgres_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "fred"
    image: "postgres:alpine"

  locust_master:
    container_name: locust_master
    image: locustio/locust
    ports:
      - "8089:8089"
    volumes:
      - ../locust:/mnt/locust
    command: -f /mnt/locust/homepage_locust.py --master -H http://web:8080
    environment:
      TARGET_HOST: web

  locust_worker:
    container_name: locust_worker
    image: locustio/locust
    volumes:
      - ../locust:/mnt/locust
    command: -f /mnt/locust/homepage_locust.py --worker --master-host locust_master