version: '3.3'
services:
  web:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      POSTGRES_PASSWORD: fred
      POSTGRES_USERNAME: postgres
      POSTGRES_HOST: jdbc:postgresql://postgres:5432/postgres
      APP_PORT: 8080

  frontend:
    container_name: frontend_react
    build: ./frontend_react
    volumes:
      - './frontend:/app'
      - '/app/node_modules'
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true

  postgres:
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "fred"
    image: "postgres:alpine"
