version: '3'
services:
  web:
    container_name: waiterapp_backend
    build: ../.
    depends_on:
      - postgres
    environment:
      POSTGRES_PASSWORD: fred
      POSTGRES_USERNAME: postgres
      POSTGRES_HOST: jdbc:postgresql://postgres:5432/postgres
      APP_PORT: 8080
    ports:
      - "8080:8080"

  postgres:
    container_name: postgres_db
    environment:
      POSTGRES_PASSWORD: "fred"
    image: "postgres:alpine"
    ports:
      - "5432:5432"

  frontend:
    container_name: frontend_react
    build: ./frontend_react
    volumes:
      - './frontend:/app'
      - '/app/node_modules'
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true

  e2e:
    build: ./e2e
    container_name: cypress
    depends_on:
      - web
    environment:
      - CYPRESS_baseUrl=http://web:8080
    command: npx cypress run
    volumes:
      - ./e2e/cypress:/app/cypress
      - ./e2e/cypress.config.js:/app/cypress.config.js
