version: '3'
services:
  web:
    container_name: waiterapp_backend
    build: ../.
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      POSTGRES_PASSWORD: fred
      POSTGRES_USERNAME: postgres
      POSTGRES_HOST: jdbc:postgresql://postgres:5432/postgres
      APP_PORT: 8080

  postgres:
    container_name: postgres_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "fred"
    image: "postgres:alpine"

  e2e:
    build: ./e2e
    container_name: cypress
    depends_on:
      - web
    environment:
      - CYPRESS_baseUrl=http://web:8080
    command: npx cypress run
    volumes:
      - ./e2e/cypress:/app/cypress
      - ./e2e/cypress.config.js:/app/cypress.config.js
